### PR TITLE
Added option to turn off PSVITA from the Adrenaline menu

### PR DESCRIPTION
**Pull request by theheroGAC**
Added option to turn off PSVITA from the Adrenaline menu

### CODE REVIEW

**Comment by TheOfficialFloW** [comment]
Please change to 'Shutdown device'

**Comment by theheroGAC** [comment]
Updated in Shutdown Device (unlock me on twitter in i did nothing i just gave one like) Thank you :)

**Comment by TheOfficialFloW** [comment]
Please move the entry below the enter standby mode too.

**Comment by theheroGAC** [comment]
updated below standby mode 👍

**Pull request merged**
